<a href="https://colab.research.google.com/github/MuhammadAliZaidi/DSA/blob/main/Random_0_1_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Random Tensor

a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

In [2]:
import torch

In [ ]:
# Creating a random tensor of size (2,3)
random_tensor= torch.rand(2,3)
random_tensor

tensor([[0.8932, 0.0511, 0.3323],
        [0.8876, 0.1064, 0.1285]])

In [ ]:
# Creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
#heigth,width , colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and Ones Tensors

In [5]:
zero=torch.zeros(size=(3,4))
print(zero)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [6]:
ones=torch.ones(size=(3,4))
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [8]:
ones.dtype

torch.float32

Creating a range of Tensor and tensor-like





In [16]:
zero_to_nine=torch.arange(start=0,end=10,step=1)
print(zero_to_nine)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [17]:
even=torch.arange(start=2,end=101,step=2)
print(even)
# the result will be tensor([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,
  #      30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,
  #      58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,
  #     86,  88,  90,  92,  94,  96,  98, 100])

tensor([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,
         30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,
         58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,
         86,  88,  90,  92,  94,  96,  98, 100])


In [18]:
ZEROS=torch.zeros_like(input=even)
print(ZEROS)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])
